Pharmacien:
    type: entity
    table: pharmacien
    id:
        ref:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nom:
            type: string
            nullable: false
            length: 30
            fixed: false
            comment: ''
        prénom:
            type: string
            nullable: false
            length: 30
            fixed: false
            comment: ''
        cin:
            type: decimal
            nullable: false
            precision: 10
            scale: 0
            comment: ''
        etat:
            type: string
            nullable: false
            length: 20
            fixed: false
            comment: ''
        numtel:
            type: string
            nullable: true
            length: 20
            fixed: false
            comment: ''
        email:
            type: string
            nullable: true
            length: 30
            fixed: false
            comment: ''
    lifecycleCallbacks: {  }
