Service:
    type: entity
    table: service
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nom:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
        categorie:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
        etat:
            type: string
            nullable: false
            length: 20
            fixed: false
            comment: ''
        description:
            type: string
            nullable: true
            length: 2000
            fixed: false
            comment: ''
    manyToMany:
        idPharmacie:
            targetEntity: Pharmacie
            cascade: {  }
            mappedBy: idService
            inversedBy: null
            joinTable: null
            orderBy: null
    lifecycleCallbacks: {  }
