Utils:
    type: entity
    table: utils
    id:
        var:
            type: string
            nullable: false
            length: 20
            fixed: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        valeur:
            type: string
            nullable: true
            length: 200
            fixed: false
            comment: ''
    lifecycleCallbacks: {  }
